# Generated by Django 3.1 on 2020-08-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='item',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
