# Generated by Django 5.0.5 on 2025-03-31 04:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20200912_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stored_%(class)ss', to='inventory.container'),
        ),
        migrations.AlterField(
            model_name='item',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stored_%(class)ss', to='inventory.container'),
        ),
        migrations.CreateModel(
            name='ItemMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moved_from', to='inventory.container')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('to_container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moved_to', to='inventory.container')),
            ],
        ),
    ]
