# Generated by Django 5.0.5 on 2025-03-31 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_container_container_alter_item_container_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmovement',
            name='from_container',
        ),
    ]
