# Generated by Django 5.0.5 on 2025-04-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_itemmovement_from_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmovement',
            name='is_new_item',
            field=models.BooleanField(default=False),
        ),
    ]
